site_name: Nick Satsuro's Site
site_url: https://NickSatsuro.github.io/pyweb2/
site_description: "Это учебный проект с автоматическим деплоем и кастомной темой."
site_author: "Николай Сацуро"

theme:
  name: null
  custom_dir: theme

extra_css:
  - assets/css/style.css

nav:
  - Главная: index.md

plugins:
  - search
