site_name: My Awesome Site
site_url: https://NickSatsuro.github.io/pyweb2/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections

# Подключаем Tailwind через CDN (быстрый способ для Task 1)
extra_javascript:
  - https://cdn.tailwindcss.com

nav:
  - Главная: index.md
